### PR TITLE
Create Prodigy/ directory and add Prodigy_NER_flowchart_v2_0_0.pdf

### PR DESCRIPTION
**Pull request by damian-romero**
- [X] Create a Prodigy directory for Prodigy assets
- [X] Add new Prodigy flowchart ./Prodigy/Prodigy_NER_flowchart_v2_0_0.pdf
- [x] Update ./README.md

### CODE REVIEW

**Comment by damian-romero** [comment]
I added `Prodigy_NER_flowchart_v2_0_0.pdf` for the social media content preview, but we will probably make some final revisions to the PDF. Please don't merge this PR just yet.

**Comment by svlandeg** [comment]
Hey Damian, just FYI I set this to "draft" as you said it's not ready to merge yet - just to avoid an accidental merge.

As soon as it's ready for review/merging, you can take it out of draft again!

**Comment by polm** [comment]
Hey, I know this is still a work in progress, but I looked over it and had a few comments. 

I understand using numbered circles for end nodes should help reduce repetition and save space, but it doesn't seem to save much space and does make the graph harder to read. So maybe that should be reconsidered.

The upper-right 2 destination node should be a 1. 

In the middle-left of the graph, the decision node "does your data include..." only has a No exit. (I guess this is just because it's unfinished, but figured I'd point it out.)

I like the visuals, look forward to seeing this when it's fully ready for review!

**Comment by damian-romero** [comment]
Hey @polm 

Since we did not have any further comments from the team, I'm opening this PR again for review. We've added a dark theme because some find the colors in the light theme hard to read. About your comments:

> The upper-right 2 destination node should be a 1.
Corrected. Thanks!

> In the middle-left of the graph, the decision node "does your data include..." only has a No exit. (I guess this is just because it's unfinished, but figured I'd point it out.)
I wasn't sure which node you were talking about, but maybe it was the one that says, "Does your training data include examples of all entity types (existing and new)?". If so, there are two exits: the one on top says "no," and the one on the left says "yes."

> I understand using numbered circles for end nodes should help reduce repetition and save space, but it doesn't seem to save much space and does make the graph harder to read. So maybe that should be reconsidered.
Helena thought about your comment, and since no one else in the team commented about being unclear, we decided to keep the exit nodes as numbered circles.

**Comment by polm** [comment]
The dark theme looks good, I do think it's easier to read! 

> I wasn't sure which node you were talking about, but maybe it was the one that says, "Does your training data include examples of all entity types (existing and new)?". If so, there are two exits: the one on top says "no," and the one on the left says "yes."

You're right, I think I was just confused about the arrows here. It's definitely fine in the current version.

> Helena thought about your comment, and since no one else in the team commented about being unclear, we decided to keep the exit nodes as numbered circles.

OK, understood.

Reviewing this again, there were just a few things I noticed.

2022-10-07T19-01-55

This node in the bottom left leads to a line with `ner.manual`, then one that says "get more annotations", then `ner.manual` again. Maybe it's fine to leave the `ner.manual` off the long line coming out of this one? 

Some minor display issues...

2022-10-07T19-00-26

I noticed this weird white spot in "OR", which is there in the light and dark versions. Maybe this is just my PDF reader, but could you check if it also looks weird to you? Also less prominent and not a big deal, but in "NO" branches, there are two white dots in the "N" characters. It looks like an SVG overlap issue or something?

2022-10-07T19-07-28

It looks like there's two kinds of underline on the first line of this box? It's not visible depending on the magnification but it looks weird. I didn't see this on any of the other underlines.

Other than that I think this is OK!

**Comment by damian-romero** [comment]
@Polm
- OR and NO fixed
- ner.manual extra node fixed
- The double underline did not appear for H or me.
Thanks for the reviews!

**Pull request merged**
